version: '3.1'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    user: www-data
    volumes:
      - ./:/app/
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "mysql-local"
networks:
  default:
    driver: bridge
